### ISSUE TITLE
DaggerStoryComponent can't find in your project.(DaggerStoryComponent这个类在你的项目中找不到。)

### ISSUE THREAD

**Issue by Zhouabao** [LeeeYou/RsKotlin#1]

**Comment by Zhouabao** [comment]
DaggerStoryComponent can't find in your project ?
(DaggerStoryComponent这个类在你的项目中找不到？)

**Comment by LeeeYou** [comment]
DaggerStoryComponent是自动生成的，需要先编译工程。 @Zhouabao
