### ISSUE TITLE
构建时错误。

### ISSUE THREAD

**Issue by jinhuizxc** [LeeeYou/RsKotlin#3]
下载了你的demo，构建时提示错误：Error:Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
请问怎么解决？

**Comment by LeeeYou** [comment]
@jinhuizxc 这个是构建问题，gradle版本采用2.3.3试试。

**Comment by jinhuizxc** [comment]
好的，我试试，谢谢。
